# Generated by Django 4.2.23 on 2025-06-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
