# Generated by Django 4.2.23 on 2025-06-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0003_pdfgenerationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='processing_fee',
            field=models.FloatField(default=1.0, help_text='Multiplier for processing fee (e.g., 1.04 for 4% fee)'),
        ),
    ]
