# Generated by Django 4.2.23 on 2025-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0004_appointment_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deposit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='menu',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='num_adult',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='num_guests',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='num_kid',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='protein',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sides',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='travel_fee',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
