# Generated by Django 4.2.23 on 2025-06-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0005_appointment_allergies_appointment_deposit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='num_adult',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='num_guests',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='num_kid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sides',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='travel_fee',
        ),
        migrations.CreateModel(
            name='PricingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('adult', 'Adult'), ('kid', 'Kid'), ('noodle_rice', 'Noodle / Rice'), ('gyoza', 'Gyoza'), ('edamame', 'Edamame'), ('fm', 'Filet Mignon'), ('lobster', 'Lobster'), ('side', 'Side'), ('protein', 'Protein')], max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(blank=True, help_text='Optional: set for location-based pricing.', max_length=128)),
            ],
            options={
                'verbose_name': 'Pricing Setting',
                'verbose_name_plural': 'Pricing Settings',
                'unique_together': {('category', 'location')},
            },
        ),
    ]
