# Generated by Django 4.2.23 on 2025-06-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0006_remove_appointment_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='color_tag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
