# Generated by Django 4.2.23 on 2025-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0007_appointment_color_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='processing_fee',
            field=models.FloatField(default=0.0, help_text='Multiplier for processing fee (e.g., 1.04 for 4% fee)'),
        ),
    ]
