# Generated by Django 4.2.23 on 2025-07-14 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0008_alter_appointment_processing_fee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricingsetting',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pricingsetting',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acquity.calendar'),
        ),
        migrations.AddField(
            model_name='pricingsetting',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
        migrations.AlterField(
            model_name='pricingsetting',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='pricingsetting',
            unique_together={('category', 'currency', 'calendar')},
        ),
        migrations.RemoveField(
            model_name='pricingsetting',
            name='location',
        ),
    ]
