# Generated by Django 4.2.23 on 2025-07-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0009_alter_pricingsetting_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingsetting',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult'), ('kid', 'Kid'), ('noodle_rice', 'Noodle / Rice'), ('gyoza', 'Appetizer: Pork Gyoza'), ('edamame', 'Appetizer: Edamame'), ('fm', 'Filet Mignon (Upgraded Protein)'), ('lobster', 'Lobster Tail (Upgraded Protein)'), ('side', 'Side'), ('additional_premium_protein', 'Additional Premium protein ($15)'), ('additional_protein', 'Additional Protein ($10)')], max_length=100),
        ),
    ]
