# Generated by Django 4.2.23 on 2025-08-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquity', '0010_alter_pricingsetting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='original_timezone',
            field=models.CharField(blank=True, default='', help_text='Original timezone from Acuity (e.g., America/New_York)', max_length=50),
        ),
    ]
